#RUNTIME USED
runtime: python27
api_version: 1
threadsafe: true

#LIBRARIES USED
libraries:
  #  - name: webapp2
  #    version: latest
  - name: jinja2
    version: latest

#ROUTES FOR THE STATIC ASSETS USED
handlers:
  - url: /css
    static_dir: css

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  - url: /.*
    script: main.app
    